version: '3.9'

services:
  app:
    build: 
      context: .
    volumes:
      - .:/django
      - ./data/web:/vol/web
    container_name: django_app
    ports:
      - 8000:8000
    environment:
      - SECRET_KEY=django-insecure-p-%kq-vv_16rv+3&6+5awy)@jgf#(7xjy2rxn-wz(3dkl61)&c
      - DEBUG=1
      - DB_NAME=devo
      - DB_USER=postgres
      - DB_PASS=1234
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_DB=devo
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=1234


