# Generated by Django 4.1.7 on 2023-03-18 16:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=225, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('is_activate', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('loan_amount', models.IntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('loan_period', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('paid_months', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('starting_date', models.DateTimeField(null=True)),
                ('status', models.CharField(choices=[('Under review', 'Under review'), ('Funded', 'Funded'), ('Completed', 'Completed')], default='Under review', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Borrower',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Investor',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('balance', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='LoanProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interest_rate', models.DecimalField(decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('accepted', models.BooleanField(default=False)),
                ('loan', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.loan')),
                ('borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.borrower')),
                ('investor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.investor')),
            ],
        ),
        migrations.AddField(
            model_name='loan',
            name='borrower',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan.borrower'),
        ),
        migrations.AddField(
            model_name='loan',
            name='investor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='loan.investor'),
        ),
    ]
